### ISSUE TITLE
Teleportation Bug

### ISSUE THREAD

**Issue by jgschuma** [POINT-VR/POINT-VR-Chapter-1#28]
If the menu is opened while the teleportation button is being held down it breaks teleportation. Theoretically turning off the ability to teleport whenever the menu opens could fix this issue.

**Comment by sonalij3** [comment]
Thanks for opening this issue. This was resolved this [commit](https://github.com/POINT-VR/POINT-VR-Chapter-1/commit/6c490289ed15c9943ff323ddce0ed0b5ed23739c) yesterday.
